version: '3.8'
name: pocket-js-server

services:
  postgres:
    container_name: in-orbit
    image: bitnami/postgresql:13.16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit